#############################################################################
# Makefile for building: castle.app/Contents/MacOS/castle
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  castle.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile castle.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt5/5.2.1/mkspecs/macx-clang -I. -I. -I/usr/local/Cellar/qt5/5.2.1/lib/QtOpenGL.framework/Versions/5/Headers -I/usr/local/Cellar/qt5/5.2.1/lib/QtWidgets.framework/Versions/5/Headers -I/usr/local/Cellar/qt5/5.2.1/lib/QtXml.framework/Versions/5/Headers -I/usr/local/Cellar/qt5/5.2.1/lib/QtGui.framework/Versions/5/Headers -I/usr/local/Cellar/qt5/5.2.1/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/usr/local/Cellar/qt5/5.2.1/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt5/5.2.1/lib -framework QtOpenGL -L/opt/X11/lib -framework QtWidgets -framework QtGui -framework QtCore -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = camera.cpp \
		light.cpp \
		material.cpp \
		math.cpp \
		MyOpenGLWidget.cpp \
		scene.cpp \
		shader.cpp 
OBJECTS       = camera.o \
		light.o \
		material.o \
		math.o \
		MyOpenGLWidget.o \
		scene.o \
		shader.o
DIST          = /usr/local/Cellar/qt5/5.2.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/shell-unix.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/spec_post.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/lex.prf \
		castle.pro \
		castle.pro
QMAKE_TARGET  = castle
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = castle.app/Contents/MacOS/castle

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile castle.app/Contents/PkgInfo castle.app/Contents/Resources/empty.lproj castle.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d castle.app/Contents/MacOS/ || mkdir -p castle.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: castle.pro /usr/local/Cellar/qt5/5.2.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt5/5.2.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/shell-unix.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/spec_post.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt5/5.2.1/mkspecs/features/lex.prf \
		castle.pro \
		/usr/local/Cellar/qt5/5.2.1/lib/QtOpenGL.framework/QtOpenGL.prl \
		/usr/local/Cellar/qt5/5.2.1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt5/5.2.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt5/5.2.1/lib/QtCore.framework/QtCore.prl \
		/usr/local/Cellar/qt5/5.2.1/lib/QtXml.framework/QtXml.prl
	$(QMAKE) -o Makefile castle.pro
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/common/shell-unix.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/spec_post.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt5/5.2.1/mkspecs/features/lex.prf:
castle.pro:
/usr/local/Cellar/qt5/5.2.1/lib/QtOpenGL.framework/QtOpenGL.prl:
/usr/local/Cellar/qt5/5.2.1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt5/5.2.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt5/5.2.1/lib/QtCore.framework/QtCore.prl:
/usr/local/Cellar/qt5/5.2.1/lib/QtXml.framework/QtXml.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile castle.pro

qmake_all: FORCE

castle.app/Contents/PkgInfo: 
	@test -d castle.app/Contents || mkdir -p castle.app/Contents
	@$(DEL_FILE) castle.app/Contents/PkgInfo
	@echo "APPL????" >castle.app/Contents/PkgInfo
castle.app/Contents/Resources/empty.lproj: 
	@test -d castle.app/Contents/Resources || mkdir -p castle.app/Contents/Resources
	@touch castle.app/Contents/Resources/empty.lproj
	
castle.app/Contents/Info.plist: 
	@test -d castle.app/Contents || mkdir -p castle.app/Contents
	@$(DEL_FILE) castle.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.castle,g" -e "s,@EXECUTABLE@,castle,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt5/5.2.1/mkspecs/macx-clang/Info.plist.app >castle.app/Contents/Info.plist
dist: 
	@test -d .tmp/castle1.0.0 || mkdir -p .tmp/castle1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/castle1.0.0/ && $(COPY_FILE) --parents camera.hpp light.hpp material.hpp math.hpp MyOpenGLWidget.hpp objet.hpp readers.hpp scene.hpp shader.hpp .tmp/castle1.0.0/ && $(COPY_FILE) --parents camera.cpp light.cpp material.cpp math.cpp MyOpenGLWidget.cpp scene.cpp shader.cpp .tmp/castle1.0.0/ && (cd `dirname .tmp/castle1.0.0` && $(TAR) castle1.0.0.tar castle1.0.0 && $(COMPRESS) castle1.0.0.tar) && $(MOVE) `dirname .tmp/castle1.0.0`/castle1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/castle1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r castle.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

camera.o: camera.cpp camera.hpp \
		math.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

light.o: light.cpp light.hpp \
		math.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o light.cpp

material.o: material.cpp material.hpp \
		math.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o material.o material.cpp

math.o: math.cpp math.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o math.o math.cpp

MyOpenGLWidget.o: MyOpenGLWidget.cpp MyOpenGLWidget.hpp \
		/usr/local/Cellar/qt5/5.2.1/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/usr/local/Cellar/qt5/5.2.1/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/usr/local/Cellar/qt5/5.2.1/lib/QtGui.framework/Versions/5/Headers/QOpenGLVertexArrayObject \
		/usr/local/Cellar/qt5/5.2.1/lib/QtGui.framework/Versions/5/Headers/qopenglvertexarrayobject.h \
		/usr/local/Cellar/qt5/5.2.1/lib/QtGui.framework/Versions/5/Headers/QOpenGLBuffer \
		/usr/local/Cellar/qt5/5.2.1/lib/QtGui.framework/Versions/5/Headers/qopenglbuffer.h \
		math.hpp \
		camera.hpp \
		shader.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyOpenGLWidget.o MyOpenGLWidget.cpp

scene.o: scene.cpp scene.hpp \
		math.hpp \
		camera.hpp \
		light.hpp \
		material.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o scene.cpp

shader.o: shader.cpp shader.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shader.o shader.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

